sudo: required
services:
  - docker

before_install:
  - docker build -t izhal/docker-react -f Dockerfile.dev .

scripts:
  - docker run izhal/docker-react npm run coverage

deploy:
  provider: pages
  repo: 'izhal27/pages-2'
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
