language: node_js
node_js:
  - stable
sudo: required
services:
  - docker
# cache:
#   directories:
#     - build
#     - .cache

before_install:
  - docker build -t izhal/docker-react -f Dockerfile.dev .

scripts:
  - docker run izhal/docker-react npm run coverage

deploy:
  provider: pages
  repo: 'izhal27/pages-2'
  # local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
