version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: izhal/fronted.dev
    volumes:
      - /home/app/node_modules
      - ./:/home/app
    ports:
      - '3000:3000'
    stdin_open: true
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: izhal/fronted.test
    volumes:
      - /home/app/node_modules
      - ./:/home/app
    command: ['npm', 'run', 'test']
    stdin_open: true
    tty: true
